version: "3"

tasks:
  plan:
    desc: Terraform plan
    cmds:
      - op run --env-file='.env' -- terraform plan --out tf.plan

  apply:
    desc: Terraform apply
    cmds:
      - op run --env-file='.env' -- terraform apply tf.plan
